### ISSUE TITLE
[fix] 아티클 관련 조회 - thumbnailUrl null 값 응답

### ISSUE THREAD

**Issue by hyeongwoo-LEE** [Do-it-Comm-it/DoitCommit-back-jpa#84]
아티클 관련 모든 조회 api에서 thumbnailUrl 값이 null 값으로 응답되고 있어 화면에 등록된 이미지가 조회되지 않는 이슈가 있다.

**Comment by hyeongwoo-LEE** [comment]
게시글 저장 시 아티클 이미지 저장이 제대로 되고 있지 않다. @corazon4815
이미지 드랍 시 S3에 저장이 성공하여 Board 객체의 content 필드의 이미지 태그에는 입력이 되었지만 게시글 저장 시 BoardImage 가 DB에는 저장이 되고 있지 않아 아티클에 해당하는 이미지 조회 시 이미지 관련 DB 데이터가 조회되고 있지 않고 있다.

**Comment by corazon4815** [comment]
프론트 페이로드 확인해보니 에디터 이미지 관련 바뀐 변수들이 프론트에 아직 적용이 안돼있음 적용되면 테스트해볼게요!

**Comment by corazon4815** [comment]
바뀐 변수들 프론트 적용 완료 후 썸네일 나오는거 테스트 완료했습니다
